#seconds BBBBBBBBBBBBBBBBBBBBBBBb
motion_start_time: 
  0: [8]


#TCP frame [M] / degree ZYX angle 
motion_task: 
  0: [-0.12, 0, 0.02, 0, -25, 0]  

 
#TCP frame [N]
desired_force:
  0: [0,0,0,0,0,0]








